name: Run Workflows
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  run-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  call-bump-version:
    uses: ./.github/workflows/bump-version.yml
  call-npm-publish:
    needs: call-bump-version
    uses: ./.github/workflows/npm-publish-github-packages.yml