name: Run Workflows
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  call-workflow1:
    uses: ./.github/workflows/bump-version.yml
  call-workflow2:
    needs: call-workflow1
    uses: ./.github/workflows/npm-publish-github-packages.yml